In [18]:
import pandas as pd
import numpy as np
from sklearn.model_selection import cross_val_score
from sklearn.linear_model import LinearRegression

In [19]:
data=pd.read_csv('/Users/omgajipara/Desktop/Data Science/AI:ML/Machine Learning/Supervised Learning/Regression/Simple_Linear_Regression/SimpleLinearRegression.csv')
data

cgpa  package
0    6.89     3.26
1    5.12     1.98
2    7.82     3.25
3    7.42     3.67
4    6.94     3.57
..    ...      ...
195  6.93     2.46
196  5.89     2.57
197  7.21     3.24
198  7.63     3.96
199  6.22     2.33

[200 rows x 2 columns]

In [20]:
x=data.iloc[:,:-1]
y=data['package']

In [25]:
p=cross_val_score(LinearRegression(),x,y,cv=5)
p.sort()
p*100

array([70.88712673, 75.39804264, 75.68383749, 78.0867752 , 79.05176315])

In [7]:
new_data=data.head(10)
x_new=new_data.iloc[:,:-1]
y_new=new_data['package']

In [5]:
from sklearn.model_selection import LeaveOneOut,LeavePOut,KFold,StratifiedKFold

# LeaveOneOut

In [40]:
from sklearn.model_selection import cross_val_score, LeaveOneOut
from sklearn.linear_model import LinearRegression
import numpy as np

# 1. LeaveOneOut split printing
lono = LeaveOneOut()
for train_index, test_index in lono.split(x_new, y_new):
    print("Train:", train_index, "Test:", test_index)


'''p = cross_val_score(LinearRegression(), x, y, cv=LeaveOneOut())
p_sorted = np.sort(p)
p_percentage = p_sorted * 100

print("Sorted CV Scores in %:", p_percentage)'''


Train: [1 2 3 4 5 6 7 8 9] Test: [0]
Train: [0 2 3 4 5 6 7 8 9] Test: [1]
Train: [0 1 3 4 5 6 7 8 9] Test: [2]
Train: [0 1 2 4 5 6 7 8 9] Test: [3]
Train: [0 1 2 3 5 6 7 8 9] Test: [4]
Train: [0 1 2 3 4 6 7 8 9] Test: [5]
Train: [0 1 2 3 4 5 7 8 9] Test: [6]
Train: [0 1 2 3 4 5 6 8 9] Test: [7]
Train: [0 1 2 3 4 5 6 7 9] Test: [8]
Train: [0 1 2 3 4 5 6 7 8] Test: [9]


'p = cross_val_score(LinearRegression(), x, y, cv=LeaveOneOut())\np_sorted = np.sort(p)\np_percentage = p_sorted * 100\n\nprint("Sorted CV Scores in %:", p_percentage)'

In [32]:
from sklearn.metrics import r2_score

In [35]:
p = cross_val_score(LinearRegression(), x, y, cv=5)
p.sort()
p * 100
p

array([0.70887127, 0.75398043, 0.75683837, 0.78086775, 0.79051763])

# LeavePOut

In [ ]:
lopo=LeavePOut(p=2)
for train,test in lopo.split(x_new,y_new):
    print(train,test)

[2 3 4 5 6 7 8 9] [0 1]
[1 3 4 5 6 7 8 9] [0 2]
[1 2 4 5 6 7 8 9] [0 3]
[1 2 3 5 6 7 8 9] [0 4]
[1 2 3 4 6 7 8 9] [0 5]
[1 2 3 4 5 7 8 9] [0 6]
[1 2 3 4 5 6 8 9] [0 7]
[1 2 3 4 5 6 7 9] [0 8]
[1 2 3 4 5 6 7 8] [0 9]
[0 3 4 5 6 7 8 9] [1 2]
[0 2 4 5 6 7 8 9] [1 3]
[0 2 3 5 6 7 8 9] [1 4]
[0 2 3 4 6 7 8 9] [1 5]
[0 2 3 4 5 7 8 9] [1 6]
[0 2 3 4 5 6 8 9] [1 7]
[0 2 3 4 5 6 7 9] [1 8]
[0 2 3 4 5 6 7 8] [1 9]
[0 1 4 5 6 7 8 9] [2 3]
[0 1 3 5 6 7 8 9] [2 4]
[0 1 3 4 6 7 8 9] [2 5]
[0 1 3 4 5 7 8 9] [2 6]
[0 1 3 4 5 6 8 9] [2 7]
[0 1 3 4 5 6 7 9] [2 8]
[0 1 3 4 5 6 7 8] [2 9]
[0 1 2 5 6 7 8 9] [3 4]
[0 1 2 4 6 7 8 9] [3 5]
[0 1 2 4 5 7 8 9] [3 6]
[0 1 2 4 5 6 8 9] [3 7]
[0 1 2 4 5 6 7 9] [3 8]
[0 1 2 4 5 6 7 8] [3 9]
[0 1 2 3 6 7 8 9] [4 5]
[0 1 2 3 5 7 8 9] [4 6]
[0 1 2 3 5 6 8 9] [4 7]
[0 1 2 3 5 6 7 9] [4 8]
[0 1 2 3 5 6 7 8] [4 9]
[0 1 2 3 4 7 8 9] [5 6]
[0 1 2 3 4 6 8 9] [5 7]
[0 1 2 3 4 6 7 9] [5 8]
[0 1 2 3 4 6 7 8] [5 9]
[0 1 2 3 4 5 8 9] [6 7]
[0 1 2 3 4 5 7 9] [6 8]
[0 1 2 3 4 5 7 8

In [27]:
p=cross_val_score(LinearRegression(),x,y,cv=LeavePOut(p=2))
p.sort()
p*100

array([-1.82288625e+06, -1.54994061e+06, -1.47243469e+06, ...,
        9.99969903e+01,  9.99979086e+01,  9.99989797e+01], shape=(19900,))

# KFold

In [13]:
kf=KFold(n_splits=5)
for train,test in kf.split(x_new,y_new):
    print(train,test)

[2 3 4 5 6 7 8 9] [0 1]
[0 1 4 5 6 7 8 9] [2 3]
[0 1 2 3 6 7 8 9] [4 5]
[0 1 2 3 4 5 8 9] [6 7]
[0 1 2 3 4 5 6 7] [8 9]


In [36]:
p=cross_val_score(LinearRegression(),x,y,cv=KFold(n_splits=5))
p.sort()
p*100

array([70.88712673, 75.39804264, 75.68383749, 78.0867752 , 79.05176315])

# StratifiedKFold
# only for classification

In [ ]:
#onlyworks on classification
stkf=StratifiedKFold(n_splits=5)

for train,test in stkf.split(x_new,y_new):
    print(train,test)

In [ ]:
p=cross_val_score(LinearRegression(),x,y,cv=StratifiedKFold(n_splits=5))
p.sort()
p*100